"""Render Markdown maths to PNGs and build an offline article preview.

Run from the repository root: python article/render_article.py
Requires matplotlib (project dependency) and mistune (installed with nbconvert).
The editable source is medium-article.md; generated files are overwritten.
"""
from pathlib import Path
import html
import re
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import mathtext
from PIL import Image
import mistune

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'medium-article.md'
ASSETS = ROOT / 'assets' / 'equations'
ASSETS.mkdir(parents=True, exist_ok=True)
plt.rcParams.update({'mathtext.fontset': 'stix', 'font.family': 'STIXGeneral'})
text = SOURCE.read_text()
# A small scientific figure explains the hinge in the activation.
import numpy as np
z = np.linspace(-4, 4, 401)
fig, ax = plt.subplots(figsize=(7, 3.8))
ax.axvspan(-4, 0, color='#eef0f3')
ax.plot(z, np.maximum(0, z), color='#176a8a', linewidth=3)
ax.axvline(0, color='#777777', linewidth=.8, linestyle='--')
ax.scatter([-3, 2], [0, 2], color='#176a8a', s=38, zorder=3)
ax.annotate('ReLU(−3) = 0', (-3, 0), xytext=(-3.8, .9),
            arrowprops={'arrowstyle': '->', 'color': '#555555'}, fontsize=12)
ax.annotate('ReLU(2) = 2', (2, 2), xytext=(.7, 3.1),
            arrowprops={'arrowstyle': '->', 'color': '#555555'}, fontsize=12)
ax.text(-3.7, -.65, 'Inactive: derivative 0', fontsize=12, color='#555555')
ax.text(.5, -.65, 'Active: derivative 1', fontsize=12, color='#176a8a')
ax.set(xlim=(-4, 4), ylim=(-.9, 4.4), xlabel='Weighted sum before activation, z',
       ylabel='ReLU(z)', title='ReLU: a hinge at zero')
ax.spines[['top', 'right']].set_visible(False)
ax.grid(alpha=.18)
fig.tight_layout()
fig.savefig(ROOT / 'assets' / 'relu-explained.png', dpi=180, facecolor='white')
plt.close(fig)
widths = {}
manifest = []

def display(match):
    formula = match.group(1).strip()
    number = len(manifest) + 1
    name = f'equation-{number:02d}.png'
    target = ASSETS / name
    # MathText uses the same subset of TeX used by these equations; no TeX install.
    from matplotlib.font_manager import FontProperties
    mathtext.math_to_image('$' + formula + '$', target, prop=FontProperties(size=21),
                          dpi=220, color='#20252b')
    with Image.open(target) as picture:
        widths[name] = round(picture.width * 96 / 220)
    manifest.append((number, formula, name))
    alt = formula.replace('\\', '').replace('[', '(').replace(']', ')')
    return f'\n![Equation {number}: {alt}](assets/equations/{name})\n'

medium = re.sub(r'^\$\$\n(.*?)\n\$\$', display, text, flags=re.M | re.S)
# Medium copy uses Unicode for short inline symbols; displayed maths stays in images.
inline = {
    's_i': 'sᵢ', 'h_i': 'hᵢ', 'r_i': 'rᵢ', 'y_i': 'yᵢ',
    'v_{ij}': 'vᵢⱼ', '\\mu_j': 'μⱼ', '\\sigma_j': 'σⱼ',
    '\\mathbf{x}_i': 'xᵢ', 'b': 'b', '\\theta=(\\mathbf{w},b)': 'θ = (w, b)',
    'n': 'n', 'i': 'i', 'j': 'j', 'X': 'X', '\\eta>0': 'η > 0', 'p_i': 'pᵢ',
    '-\\log p_i': '−log pᵢ', '-\\log(1-p_i)': '−log(1 − pᵢ)',
    't_i\\in\\{-1,+1\\}': 'tᵢ ∈ {−1, +1}', '\\theta': 'θ', 'a': 'a',
}

def short_math(match):
    formula = match.group(1)
    if formula not in inline:
        raise ValueError(f'Add a readable inline equivalent for: {formula}')
    return inline[formula]

medium = re.sub(r'(?<!\$)\$([^$\n]+)\$(?!\$)', short_math, medium)
(ROOT / 'medium-ready.md').write_text(medium)
body = mistune.create_markdown(plugins=['table'])(medium)
for name, width in widths.items():
    body = body.replace(f'<img src="assets/equations/{name}"',
                        f'<img class="equation" style="width:{width}px" src="assets/equations/{name}"')
style = '''body{max-width:780px;margin:60px auto;padding:0 24px;color:#222;font:20px/1.7 Georgia,serif}
h1,h2,h3{font-family:system-ui;line-height:1.25}h1{font-size:40px}h2{margin-top:48px;font-size:28px}h3{margin-top:32px;font-size:22px}
img{max-width:100%;height:auto}.equation{display:block;margin:28px auto}table{border-collapse:collapse;font:16px/1.5 system-ui;width:100%}
td,th{padding:10px;text-align:left;border-bottom:1px solid #ddd}a{color:#176a4d}code{font-size:.85em}'''
(ROOT / 'medium-article.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>From Linear Regression to a Neural Network</title><style>'+style+'</style></head><body><article>'+body+'</article></body></html>')
(ROOT / 'equations.md').write_text('# Equation assets\n\nGenerated by `python article/render_article.py`. Numbering follows the article.\n\n' + '\n\n'.join(f'## {n:02d}\n\n$$\n{formula}\n$$\n\n`assets/equations/{name}`' for n,formula,name in manifest)+'\n')
print(f'Rendered {len(manifest)} equations and an offline HTML preview.')
